import { StyleSheet } from 'react-native';

import {
  colors,
  elevation,
  fontWeight,
  opacity,
  radius,
  spacing,
  textStyle,
  typography,
  zIndex,
} from '@/mobile/app/shared/theme/tokens';

export const mapScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  searchLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: zIndex.floating,
    // Android stacks siblings by elevation before zIndex; the layer has to
    // out-rank the shadows of the floating controls around it.
    elevation: elevation.modal.elevation,
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  searchControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
    paddingLeft: spacing.md,
    paddingRight: spacing.xs,
    borderRadius: radius.xl,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    ...elevation.floating,
  },
  searchInputWrap: {
    flex: 1,
    minHeight: 38,
    paddingRight: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    minHeight: 38,
    ...typography.captionText,
    fontWeight: fontWeight.regular,
    color: colors.text,
    backgroundColor: 'transparent',
    includeFontPadding: false,
    paddingVertical: spacing.sm,
    textAlignVertical: 'center',
  },
  clearButton: {
    width: 28,
    height: 28,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchActionGroup: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  floatingSearchAction: {
    width: 40,
    height: 40,
    borderRadius: radius.xl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    ...elevation.floating,
  },
  refreshButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  filterButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  filterMenu: {
    width: 190,
    alignSelf: 'flex-end',
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: spacing.sm,
    gap: spacing.xs,
    ...elevation.floating,
  },
  filterMenuTitle: {
    paddingHorizontal: spacing.xs,
    paddingBottom: spacing.xs,
    ...typography.metadataText,
    fontWeight: fontWeight.strong,
    color: colors.textSoft,
  },
  filterOption: {
    minHeight: 36,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  filterOptionActive: {
    backgroundColor: colors.surfaceMuted,
  },
  filterOptionDot: {
    width: 8,
    height: 8,
    borderRadius: radius.xs,
  },
  filterOptionDotNone: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: colors.textSoft,
  },
  filterOptionText: textStyle('metadataText', colors.textMuted),
  filterOptionTextActive: {
    color: colors.text,
  },
  resultsLayer: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    // Just under the search layer, whose suggestions may overlap it.
    zIndex: zIndex.floating - 1,
    elevation: elevation.modal.elevation - 1,
  },
  resultsLayerShort: {
    justifyContent: 'flex-end',
  },
  resultsCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    ...elevation.floating,
  },
  resultsScroll: {
    flexGrow: 0,
  },
  resultsScrollContent: {
    paddingBottom: spacing.xs,
  },
  resultsHeader: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceMuted,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  resultsHeaderText: textStyle('metadataText', colors.textSoft, fontWeight.strong),
  resultRow: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  resultRowLast: {
    borderBottomWidth: 0,
  },
  resultTitle: textStyle('metadataText', colors.text, fontWeight.strong),
  resultAddress: {
    marginTop: spacing.xs,
    ...typography.metadataText,
    fontWeight: fontWeight.regular,
    color: colors.textMuted,
  },
  emptyResultsCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  emptyResultsTitle: textStyle('metadataText', colors.text, fontWeight.strong),
  emptyResultsDescription: {
    marginTop: spacing.xs,
    ...typography.metadataText,
    fontWeight: fontWeight.regular,
    color: colors.textMuted,
  },
  map: {
    flex: 1,
    backgroundColor: colors.mapBackground,
  },
  mapPlaceholder: {
    flex: 1,
    backgroundColor: colors.mapBackground,
  },
  locateButton: {
    position: 'absolute',
    right: spacing.md,
    width: 40,
    height: 40,
    borderRadius: radius.xl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    ...elevation.floating,
  },
  locateButtonDisabled: {
    opacity: opacity.disabled,
  },
  reopenEditorButton: {
    position: 'absolute',
    left: spacing.md,
    right: 60,
    minHeight: 46,
    borderRadius: radius.lg,
    backgroundColor: colors.text,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    ...elevation.floating,
  },
  reopenEditorBody: {
    flex: 1,
    gap: spacing.xxs,
  },
  reopenEditorTitle: textStyle('metadataText', colors.onPrimary, fontWeight.strong),
  reopenEditorSubtitle: textStyle('metadataText', colors.onDarkMuted),
});
