import { StyleSheet } from 'react-native';

import { colors, fontWeight, radius, spacing, textStyle, typography } from '@/mobile/app/shared/theme/tokens';

export const mapScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  searchLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 10,
    gap: spacing.sm,
    elevation: 8,
    paddingHorizontal: spacing.md,
  },
  searchControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 48,
    paddingLeft: spacing.md,
    paddingRight: spacing.xs,
    borderRadius: radius.xl,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    shadowColor: colors.text,
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  searchInputWrap: {
    flex: 1,
    minHeight: 44,
    paddingRight: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    minHeight: 44,
    ...typography.captionText,
    fontWeight: fontWeight.regular,
    color: colors.text,
    backgroundColor: 'transparent',
    includeFontPadding: false,
    paddingVertical: spacing.sm,
    textAlignVertical: 'center',
  },
  clearButton: {
    width: 44,
    height: 44,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchActionGroup: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  floatingSearchAction: {
    width: 44,
    height: 44,
    borderRadius: radius.xl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    elevation: 4,
  },
  refreshButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  filterButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  filterMenu: {
    width: 190,
    alignSelf: 'flex-end',
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: spacing.sm,
    gap: spacing.xs,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  filterMenuTitle: {
    paddingHorizontal: spacing.xs,
    paddingBottom: spacing.xs,
    ...typography.metadataText,
    fontWeight: fontWeight.strong,
    color: colors.textSoft,
  },
  filterOption: {
    minHeight: 44,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  filterOptionActive: {
    backgroundColor: colors.surfaceMuted,
  },
  filterOptionDot: {
    width: 8,
    height: 8,
    borderRadius: radius.xs,
  },
  filterOptionDotNone: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: colors.textSoft,
  },
  filterOptionText: textStyle('metadataText', colors.textMuted),
  filterOptionTextActive: {
    color: colors.text,
  },
  resultsLayer: {
    position: 'absolute',
    left: 10,
    right: 10,
    zIndex: 9,
    elevation: 7,
  },
  resultsLayerShort: {
    justifyContent: 'flex-end',
  },
  resultsCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    elevation: 6,
  },
  resultsScroll: {
    flexGrow: 0,
  },
  resultsScrollContent: {
    paddingBottom: spacing.xs,
  },
  resultsHeader: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceMuted,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  resultsHeaderText: textStyle('metadataText', colors.textSoft, fontWeight.strong),
  resultRow: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  resultRowLast: {
    borderBottomWidth: 0,
  },
  resultTitle: textStyle('metadataText', colors.text, fontWeight.strong),
  resultAddress: {
    marginTop: spacing.xs,
    ...typography.metadataText,
    fontWeight: fontWeight.regular,
    color: colors.textMuted,
  },
  emptyResultsCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  emptyResultsTitle: textStyle('metadataText', colors.text, fontWeight.strong),
  emptyResultsDescription: {
    marginTop: spacing.xs,
    ...typography.metadataText,
    fontWeight: fontWeight.regular,
    color: colors.textMuted,
  },
  map: {
    flex: 1,
    backgroundColor: colors.mapBackground,
  },
  mapPlaceholder: {
    flex: 1,
    backgroundColor: colors.mapBackground,
  },
  locateButton: {
    position: 'absolute',
    right: 12,
    width: 44,
    height: 44,
    borderRadius: radius.xl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  locateButtonDisabled: {
    opacity: 0.72,
  },
  reopenEditorButton: {
    position: 'absolute',
    left: 12,
    right: 60,
    minHeight: 46,
    borderRadius: radius.lg,
    backgroundColor: colors.text,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    shadowColor: colors.text,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  reopenEditorBody: {
    flex: 1,
    gap: spacing.xxs,
  },
  reopenEditorTitle: textStyle('metadataText', colors.onPrimary, fontWeight.strong),
  reopenEditorSubtitle: textStyle('metadataText', colors.onDarkSubtle),
});
