import { StyleSheet } from 'react-native';

import { colors, radius, typography } from '@/mobile/app/shared/theme/tokens';

export const mapScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  searchLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 10,
    gap: 6,
    elevation: 8,
    paddingHorizontal: 10,
  },
  searchControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 48,
    paddingLeft: 10,
    paddingRight: 4,
    borderRadius: radius.xl,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    shadowColor: colors.text,
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  searchInputWrap: {
    flex: 1,
    minHeight: 44,
    paddingRight: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  searchInput: {
    flex: 1,
    minHeight: 44,
    fontSize: 13,
    lineHeight: 18,
    color: colors.text,
    backgroundColor: 'transparent',
    includeFontPadding: false,
    paddingVertical: 6,
    textAlignVertical: 'center',
  },
  clearButton: {
    width: 44,
    height: 44,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchActionGroup: {
    flexDirection: 'row',
    gap: 4,
  },
  floatingSearchAction: {
    width: 44,
    height: 44,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    elevation: 4,
  },
  refreshButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  filterButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  filterMenu: {
    width: 190,
    alignSelf: 'flex-end',
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 8,
    gap: 4,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  filterMenuTitle: {
    paddingHorizontal: 4,
    paddingBottom: 4,
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSoft,
  },
  filterOption: {
    minHeight: 44,
    borderRadius: radius.md,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filterOptionActive: {
    backgroundColor: colors.surfaceMuted,
  },
  filterOptionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  filterOptionDotNone: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: colors.textSoft,
  },
  filterOptionText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
  },
  filterOptionTextActive: {
    color: colors.text,
  },
  resultsLayer: {
    position: 'absolute',
    left: 10,
    right: 10,
    zIndex: 9,
    elevation: 7,
  },
  resultsLayerShort: {
    justifyContent: 'flex-end',
  },
  resultsCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    elevation: 6,
  },
  resultsScroll: {
    flexGrow: 0,
  },
  resultsScrollContent: {
    paddingBottom: 4,
  },
  resultsHeader: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: colors.surfaceMuted,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  resultsHeaderText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSoft,
  },
  resultRow: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  resultRowLast: {
    borderBottomWidth: 0,
  },
  resultTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  resultAddress: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    color: colors.textMuted,
  },
  emptyResultsCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  emptyResultsTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  emptyResultsDescription: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    color: colors.textMuted,
  },
  map: {
    flex: 1,
    backgroundColor: colors.mapBackground,
  },
  mapPlaceholder: {
    flex: 1,
    backgroundColor: colors.mapBackground,
  },
  locateButton: {
    position: 'absolute',
    right: 12,
    width: 44,
    height: 44,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  locateButtonDisabled: {
    opacity: 0.72,
  },
  reopenEditorButton: {
    position: 'absolute',
    left: 12,
    right: 60,
    minHeight: 46,
    borderRadius: radius.lg,
    backgroundColor: colors.text,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    shadowColor: colors.text,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  reopenEditorBody: {
    flex: 1,
    gap: 2,
  },
  reopenEditorTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.onPrimary,
  },
  reopenEditorSubtitle: {
    ...typography.metadataText,
    color: colors.onDarkSubtle,
  },
});
