import { StyleSheet } from 'react-native';

import {
  colors,
  fontWeight,
  layout,
  minTouchSize,
  radius,
  textStyle,
  touch,
  typography,
} from '@/mobile/app/shared/theme/tokens';

export const discoveryTileStyles = StyleSheet.create({
  tile: {
    minHeight: 190,
    borderRadius: radius.lg,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  tileFullWidth: {
    width: '100%',
  },
  tileCompact: {
    minHeight: 0,
  },
  userTile: {
    minHeight: 0,
  },
  userTileMainAction: {
    width: '100%',
  },
  tilePressable: {
    width: '100%',
  },
  tileActionShell: {
    position: 'relative',
    width: '100%',
  },
  ownerHeader: {
    minHeight: minTouchSize,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingTop: 5,
    paddingBottom: 4,
  },
  ownerBody: {
    flex: 1,
  },
  ownerName: textStyle('labelText', colors.text),
  ownerUsername: {
    fontSize: typography.metadataText.fontSize,
    lineHeight: typography.metadataText.lineHeight,
    color: colors.textSoft,
  },
  mediaSquare: {
    height: layout.discoveryTileHeight,
    width: '100%',
    backgroundColor: colors.surfaceMuted,
  },
  placeholderSquare: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryBg,
  },
  placeholderEmoji: {
    fontSize: typography.dialogTitleText.fontSize,
  },
  visibilityBadge: {
    position: 'absolute',
    top: 4,
    left: 4,
    minHeight: 22,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
    backgroundColor: colors.darkOverlay,
    paddingHorizontal: 6,
  },
  visibilityBadgeText: textStyle('metadataText', colors.onPrimary, fontWeight.strong),
  iconBadgeRight: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.overlay,
  },
  actionBadgeColumn: {
    position: 'absolute',
    top: 4,
    right: 4,
    gap: 4,
  },
  mediaFooterRow: {
    position: 'absolute',
    left: 4,
    right: 4,
    bottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  mediaFooterBadge: {
    minHeight: 22,
    borderRadius: radius.pill,
    backgroundColor: colors.darkOverlay,
    paddingHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  mediaFooterBadgeText: textStyle('metadataText', colors.onPrimary, fontWeight.strong),
  singleActionBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: touch.android,
    height: touch.android,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    paddingTop: 4,
    paddingRight: 4,
    zIndex: 2,
  },
  singleActionBadgeVisual: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.overlay,
  },
  tileBody: {
    minHeight: 58,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 7,
  },
  tileBodyCompact: {
    minHeight: 0,
    paddingBottom: 6,
  },
  tileTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
  },
  tileTitleContent: {
    flex: 1,
    minWidth: 0,
  },
  titleActionButton: {
    width: touch.android,
    height: touch.android,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    paddingTop: 14,
    paddingRight: 8,
  },
  titleActionButtonVisual: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  titleActionButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  titleActionOverlay: {
    position: 'absolute',
    top: layout.discoveryTileHeight - 8,
    right: 0,
    zIndex: 2,
  },
  titleActionPlaceholder: {
    width: 20,
    height: 20,
  },
  tileTitle: textStyle('labelText', colors.text),
  tileDescription: {
    marginTop: 3,
    ...typography.metadataText,
    color: colors.textMuted,
  },
  listContextBar: {
    marginTop: 4,
    minHeight: 36,
    borderRadius: radius.md,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: 4,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  listContextCover: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: colors.surfaceMuted,
  },
  listContextCoverFallback: {
    width: 24,
    height: 24,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  listContextBody: {
    flex: 1,
    minWidth: 0,
  },
  listContextTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  listContextTitle: textStyle('labelText', colors.text),
  listContextMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 1,
  },
  listContextMetaText: textStyle('metadataText', colors.textSoft),
  listContextMetaTextPrivate: {
    color: colors.visibilityPrivate,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  metaLike: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  tileMeta: textStyle('metadataText', colors.textSoft),
  tileTimestamp: {
    marginTop: 3,
    fontSize: typography.metadataText.fontSize,
    lineHeight: typography.metadataText.lineHeight,
    color: colors.textSoft,
  },
  tileMetaSummary: {
    marginTop: 3,
    ...typography.metadataText,
    color: colors.textSoft,
  },
  tileSecondaryRow: {
    minHeight: 16,
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tileTimestampInline: {
    flex: 1,
    ...typography.metadataText,
    color: colors.textSoft,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingText: textStyle('metadataText', colors.warningText),
  photoCountBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 20,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: radius.pill,
    backgroundColor: colors.darkOverlay,
    borderWidth: 1,
    borderColor: colors.controlsBorder,
  },
  photoCountGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  photoCountDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: colors.controlsDivider,
  },
  photoCountText: textStyle('metadataText', colors.onPrimary, fontWeight.strong),
  userCover: {
    height: 50,
    backgroundColor: colors.coverFallback,
  },
  userAvatarWrap: {
    marginTop: -18,
    paddingHorizontal: 8,
  },
  userAvatarFrame: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.surface,
    overflow: 'hidden',
  },
  userTileBody: {
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 7,
  },
  userTileBodyMain: {
    paddingBottom: 0,
  },
  followButton: {
    minHeight: minTouchSize,
    marginHorizontal: 8,
    marginTop: 6,
    marginBottom: 7,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  followButtonPassive: {
    backgroundColor: colors.surfaceMuted,
  },
  followButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  followButtonText: textStyle('labelText', colors.onPrimary),
  followButtonTextPassive: {
    color: colors.textMuted,
  },
});
