import { StyleSheet } from 'react-native';

import { colors, layout, radius } from '@/mobile/app/shared/theme/tokens';

export const discoveryTileStyles = StyleSheet.create({
  tile: {
    borderRadius: radius.lg,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  tilePressable: {
    flex: 1,
  },
  ownerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 8,
  },
  ownerBody: {
    flex: 1,
  },
  ownerName: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.text,
  },
  ownerUsername: {
    fontSize: 9,
    color: colors.textSoft,
  },
  mediaSquare: {
    minHeight: 176,
    backgroundColor: colors.surfaceMuted,
  },
  placeholderSquare: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryBg,
  },
  placeholderEmoji: {
    fontSize: 26,
  },
  iconBadgeLeft: {
    position: 'absolute',
    top: 8,
    left: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkOverlay,
  },
  iconBadgeRight: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.overlay,
  },
  actionBadgeColumn: {
    position: 'absolute',
    top: 8,
    right: 8,
    gap: 6,
  },
  singleActionBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.overlay,
    zIndex: 2,
  },
  tileBody: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
  },
  tileTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  tileTitleContent: {
    flex: 1,
    minWidth: 0,
  },
  titleActionButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  titleActionButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  tileTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  tileDescription: {
    marginTop: 4,
    fontSize: 10,
    color: colors.textSoft,
  },
  listContextBar: {
    marginTop: 8,
    minHeight: 52,
    borderRadius: radius.md,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: 8,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  listContextCover: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: colors.surfaceMuted,
  },
  listContextCoverFallback: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  listContextBody: {
    flex: 1,
    minWidth: 0,
  },
  listContextTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  listContextTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.text,
  },
  listContextMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 3,
  },
  listContextMetaText: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
  },
  listContextMetaTextPrivate: {
    color: colors.danger,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  metaLike: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  tileMeta: {
    fontSize: 10,
    color: colors.textSoft,
  },
  tileTimestamp: {
    marginTop: 6,
    fontSize: 9,
    lineHeight: 13,
    color: colors.textSoft,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 6,
  },
  ratingText: {
    fontSize: 10,
    color: colors.warningText,
    fontWeight: '600',
  },
  photoCountBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: radius.pill,
    backgroundColor: colors.darkOverlay,
  },
  photoCountText: {
    fontSize: 9,
    fontWeight: '700',
    color: colors.onPrimary,
  },
  userCover: {
    height: 72,
    backgroundColor: colors.userCoverFallback,
  },
  userAvatarWrap: {
    marginTop: -30,
    paddingHorizontal: 12,
  },
  userAvatarFrame: {
    width: 66,
    height: 66,
    borderRadius: 33,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 3,
    borderColor: colors.surface,
    overflow: 'hidden',
  },
  userTileBody: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
  },
  followButton: {
    minHeight: 30,
    marginTop: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  followButtonPassive: {
    backgroundColor: colors.surfaceMuted,
  },
  followButtonText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.onPrimary,
  },
  followButtonTextPassive: {
    color: colors.textMuted,
  },
});
