import { StyleSheet } from 'react-native';

import { colors, layout, radius, typography } from '@/mobile/app/shared/theme/tokens';

export const discoveryTileStyles = StyleSheet.create({
  tile: {
    minHeight: 190,
    borderRadius: radius.lg,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  tileFullWidth: {
    width: '100%',
  },
  tileCompact: {
    minHeight: 0,
  },
  userTile: {
    minHeight: 0,
  },
  tilePressable: {
    width: '100%',
  },
  ownerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingTop: 5,
    paddingBottom: 4,
  },
  ownerBody: {
    flex: 1,
  },
  ownerName: {
    fontSize: typography.compactCardTitleText.fontSize,
    lineHeight: typography.compactCardTitleText.lineHeight,
    fontWeight: '700',
    color: colors.text,
  },
  ownerUsername: {
    fontSize: typography.compactCardMetaText.fontSize,
    lineHeight: typography.compactCardMetaText.lineHeight,
    color: colors.textSoft,
  },
  mediaSquare: {
    height: layout.discoveryTileHeight,
    width: '100%',
    backgroundColor: colors.surfaceMuted,
  },
  placeholderSquare: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryBg,
  },
  placeholderEmoji: {
    fontSize: 18,
  },
  visibilityBadge: {
    position: 'absolute',
    top: 4,
    left: 4,
    minHeight: 22,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
    backgroundColor: colors.darkOverlay,
    paddingHorizontal: 6,
  },
  visibilityBadgeText: {
    fontSize: typography.compactCardMetaText.fontSize,
    fontWeight: '700',
    color: colors.onPrimary,
  },
  iconBadgeRight: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.overlay,
  },
  actionBadgeColumn: {
    position: 'absolute',
    top: 4,
    right: 4,
    gap: 4,
  },
  mediaFooterRow: {
    position: 'absolute',
    left: 4,
    right: 4,
    bottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  mediaFooterBadge: {
    minHeight: 22,
    borderRadius: radius.pill,
    backgroundColor: colors.darkOverlay,
    paddingHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  mediaFooterBadgeText: {
    fontSize: typography.compactCardMetaText.fontSize,
    fontWeight: '700',
    color: colors.onPrimary,
  },
  singleActionBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.overlay,
    zIndex: 2,
  },
  tileBody: {
    minHeight: 58,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 7,
  },
  tileBodyCompact: {
    minHeight: 0,
    paddingBottom: 6,
  },
  tileTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
  },
  tileTitleContent: {
    flex: 1,
    minWidth: 0,
  },
  titleActionButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  titleActionButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  tileTitle: {
    ...typography.compactCardTitleText,
    color: colors.text,
  },
  tileDescription: {
    marginTop: 3,
    ...typography.compactCardMetaText,
    color: colors.textMuted,
  },
  listContextBar: {
    marginTop: 4,
    minHeight: 36,
    borderRadius: radius.md,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: 4,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  listContextCover: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: colors.surfaceMuted,
  },
  listContextCoverFallback: {
    width: 24,
    height: 24,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  listContextBody: {
    flex: 1,
    minWidth: 0,
  },
  listContextTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  listContextTitle: {
    fontSize: typography.compactCardTitleText.fontSize,
    lineHeight: typography.compactCardTitleText.lineHeight,
    fontWeight: '700',
    color: colors.text,
  },
  listContextMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 1,
  },
  listContextMetaText: {
    fontSize: typography.compactCardMetaText.fontSize,
    lineHeight: typography.compactCardMetaText.lineHeight,
    fontWeight: '600',
    color: colors.textSoft,
  },
  listContextMetaTextPrivate: {
    color: colors.visibilityPrivate,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  metaLike: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  tileMeta: {
    fontSize: typography.compactCardMetaText.fontSize,
    lineHeight: typography.compactCardMetaText.lineHeight,
    fontWeight: '600',
    color: colors.textSoft,
  },
  tileTimestamp: {
    marginTop: 3,
    fontSize: typography.compactCardMetaText.fontSize,
    lineHeight: typography.compactCardMetaText.lineHeight,
    color: colors.textSoft,
  },
  tileMetaSummary: {
    marginTop: 3,
    ...typography.compactCardMetaText,
    color: colors.textSoft,
  },
  tileSecondaryRow: {
    minHeight: 16,
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tileTimestampInline: {
    flex: 1,
    ...typography.compactCardMetaText,
    color: colors.textSoft,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingText: {
    fontSize: typography.compactCardMetaText.fontSize,
    color: colors.warningText,
    fontWeight: '600',
  },
  photoCountBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 20,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: radius.pill,
    backgroundColor: colors.darkOverlay,
    borderWidth: 1,
    borderColor: colors.controlsBorder,
  },
  photoCountGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  photoCountDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: colors.controlsDivider,
  },
  photoCountText: {
    fontSize: typography.compactCardMetaText.fontSize,
    fontWeight: '700',
    color: colors.onPrimary,
  },
  userCover: {
    height: 50,
    backgroundColor: colors.coverFallback,
  },
  userAvatarWrap: {
    marginTop: -18,
    paddingHorizontal: 8,
  },
  userAvatarFrame: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.surface,
    overflow: 'hidden',
  },
  userTileBody: {
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 7,
  },
  followButton: {
    minHeight: 34,
    marginTop: 6,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  followButtonPassive: {
    backgroundColor: colors.surfaceMuted,
  },
  followButtonText: {
    fontSize: typography.compactCardTitleText.fontSize,
    fontWeight: '700',
    color: colors.onPrimary,
  },
  followButtonTextPassive: {
    color: colors.textMuted,
  },
});
