import { StyleSheet } from 'react-native';

import {
  colors,
  fontWeight,
  radius,
  spacing,
  textStyle,
  typography,
} from '@/mobile/app/shared/theme/tokens';

export const placeEditorListSelectionStyles = StyleSheet.create({
  stepContent: {
    gap: 12,
  },
  section: {
    gap: 8,
  },
  sectionTitle: textStyle('metadataText', colors.text, fontWeight.strong),
  sectionHelper: {
    marginTop: -2,
    ...typography.metadataText,
    color: colors.textSoft,
  },
  listSelectionNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: colors.warningBg,
    borderRadius: radius.md,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.warning,
    shadowColor: colors.warningText,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  listSelectionNoticeIconWrap: {
    width: 20,
    height: 20,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  listSelectionNoticeBody: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  listSelectionNoticeTitle: textStyle('metadataText', colors.warningText, fontWeight.strong),
  listSelectionNoticeText: textStyle('metadataText', colors.warningText, fontWeight.strong),
  listWrap: {
    gap: 8,
  },
  listCard: {
    minHeight: 80,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surfaceMuted,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: spacing.card,
    overflow: 'hidden',
  },
  listCardSelected: {
    backgroundColor: colors.surface,
    borderColor: colors.primary,
  },
  listCardDisabled: {
    opacity: 0.58,
  },
  listPreview: {
    width: 66,
    height: 66,
    borderRadius: radius.md,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  listPreviewPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryBg,
  },
  listPreviewEmoji: {
    fontSize: typography.title.fontSize,
  },
  listRadio: {
    width: 16,
    height: 16,
    borderRadius: radius.pill,
    borderWidth: 2,
    borderColor: colors.cardBorder,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  listRadioSelected: {
    borderColor: colors.primary,
  },
  listRadioDisabled: {
    borderColor: colors.textSoft,
    backgroundColor: colors.surfaceMuted,
  },
  listRadioInner: {
    width: 6,
    height: 6,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
  },
  listBody: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  listTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
  },
  listName: {
    flexShrink: 1,
    ...typography.metadataText,
    fontWeight: fontWeight.strong,
    color: colors.text,
  },
  listNameDisabled: {
    color: colors.textMuted,
  },
  listMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  listMeta: textStyle('metadataText', colors.textSoft, fontWeight.strong),
  listMetaDisabled: {
    color: colors.textMuted,
  },
  listPrivacyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 24,
    paddingHorizontal: 6,
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  listPrivacyText: textStyle('metadataText', colors.textMuted, fontWeight.strong),
  createListTrigger: {
    minHeight: 44,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.primary,
    backgroundColor: colors.primaryBg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  createListTriggerText: textStyle('metadataText', colors.primary, fontWeight.strong),
  createListCard: {
    gap: 10,
    borderRadius: radius.lg,
    padding: spacing.card,
    backgroundColor: colors.successBg,
    borderWidth: 1,
    borderColor: colors.secondary,
  },
  createListHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  coverPickerRow: {
    width: '100%',
    gap: 8,
  },
  coverPicker: {
    width: '100%',
    borderRadius: radius.md,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.secondary,
    backgroundColor: colors.surfaceMuted,
    gap: 10,
    padding: spacing.md,
  },
  coverPickerSelected: {
    backgroundColor: colors.surface,
  },
  coverPickerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  coverPickerHeaderCopy: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minHeight: 48,
  },
  coverPickerIconWrap: {
    width: 34,
    height: 34,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  coverPickerBody: {
    flex: 1,
    gap: 2,
  },
  coverPickerTitle: textStyle('metadataText', colors.secondary, fontWeight.strong),
  coverPickerHint: textStyle('metadataText', colors.textMuted),
  coverPickerText: textStyle('metadataText', colors.secondary, fontWeight.strong),
  selectionBadge: {
    minHeight: 30,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  selectionBadgeText: textStyle('metadataText', colors.textMuted, fontWeight.strong),
  coverClearInline: {
    alignSelf: 'flex-end',
    borderRadius: radius.pill,
    backgroundColor: colors.darkOverlay,
    alignItems: 'center',
    justifyContent: 'center',
  },
  privacyRow: {
    flexDirection: 'row',
    gap: 6,
  },
  privacyButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  privacyButtonActive: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.primary,
  },
  privateButtonActive: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.primary,
  },
  privacyText: textStyle('metadataText', colors.textMuted, fontWeight.strong),
  privacyTextActive: {
    color: colors.primary,
  },
});
