import { Platform, StyleSheet } from 'react-native';

import { colors, fontWeight, radius, textStyle, touch, typography } from '@/mobile/app/shared/theme/tokens';

const MIN_TOUCH_SIZE = Platform.OS === 'ios' ? touch.ios : touch.android;

export const placeEditorModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
  },
  panel: {
    width: '100%',
    maxWidth: 684,
    alignSelf: 'center',
    maxHeight: '88%',
    minHeight: 310,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  panelCompressed: {
    transform: [{ scale: 0.985 }],
  },
  panelBody: {
    position: 'relative',
    flex: 1,
    minHeight: 0,
  },
  panelTopArea: {
    gap: 0,
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: radius.pill,
    backgroundColor: colors.cardBorder,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cancelButton: {
    minHeight: MIN_TOUCH_SIZE,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  cancelButtonText: textStyle('metadataText', colors.textMuted, fontWeight.strong),
  headerText: {
    flex: 1,
    paddingRight: 10,
  },
  headerTitle: textStyle('compactSectionText', colors.text, fontWeight.strong),
  headerSubtitle: {
    marginTop: 2,
    ...typography.metadataText,
    fontWeight: fontWeight.regular,
    color: colors.textSoft,
  },
  headerMeta: {
    marginTop: 4,
    ...typography.metadataText,
    fontWeight: fontWeight.strong,
    color: colors.primary,
  },
  saveProgressBanner: {
    gap: 6,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  saveProgressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  saveProgressMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  saveProgressTitle: {
    flex: 1,
    ...typography.metadataText,
    fontWeight: fontWeight.strong,
    color: colors.text,
  },
  saveProgressDetail: textStyle('metadataText', colors.textMuted),
  saveProgressPercent: textStyle('metadataText', colors.primary, fontWeight.strong),
  saveProgressPercentFailed: {
    color: colors.danger,
  },
  saveProgressMenuButton: {
    width: 24,
    height: 24,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveProgressTrack: {
    height: 6,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceMuted,
    overflow: 'hidden',
  },
  saveProgressFill: {
    height: '100%',
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
  },
  saveProgressFillFailed: {
    backgroundColor: colors.danger,
  },
  saveProgressWarning: textStyle('metadataText', colors.textSoft),
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.background,
  },
  stepTitle: textStyle('metadataText', colors.text, fontWeight.strong),
  stepSubtitle: {
    marginTop: 2,
    ...typography.metadataText,
    fontWeight: fontWeight.regular,
    color: colors.textSoft,
  },
  stepDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  stepDot: {
    width: 10,
    height: 4,
    borderRadius: radius.pill,
    backgroundColor: colors.cardBorder,
  },
  stepDotActive: {
    width: 22,
    backgroundColor: colors.primary,
  },
  stepDotDone: {
    backgroundColor: colors.secondary,
  },
  contentScroll: {
    flex: 1,
    minHeight: 0,
  },
  content: {
    padding: 14,
    flexGrow: 1,
  },
  contentWithFooterBuffer: {
    paddingBottom: 32,
  },
  lockOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.glassSurface,
    paddingHorizontal: 22,
  },
  lockOverlayTitle: {
    ...typography.bodyText,
    fontWeight: fontWeight.strong,
    color: colors.text,
    textAlign: 'center',
  },
  lockOverlayDescription: {
    ...typography.metadataText,
    fontWeight: fontWeight.regular,
    color: colors.textSoft,
    textAlign: 'center',
  },
  footer: {
    flexDirection: 'row',
    gap: 8,
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
    backgroundColor: colors.surface,
    flexShrink: 0,
  },
  backButton: {
    minHeight: MIN_TOUCH_SIZE,
    borderRadius: radius.md,
    paddingHorizontal: 10,
    backgroundColor: colors.surfaceMuted,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  backButtonText: textStyle('metadataText', colors.textMuted, fontWeight.strong),
  deleteButton: {
    minHeight: MIN_TOUCH_SIZE,
    borderRadius: radius.md,
    paddingHorizontal: 10,
    backgroundColor: colors.dangerBg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  deleteButtonText: textStyle('metadataText', colors.danger, fontWeight.strong),
  nextButton: {
    flex: 1,
    minHeight: MIN_TOUCH_SIZE,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  disabledButton: {
    opacity: 0.45,
  },
  nextButtonText: textStyle('metadataText', colors.onPrimary, fontWeight.strong),
});
