import { StyleSheet } from 'react-native';

import {
  avatarSize,
  colors,
  fontWeight,
  opacity,
  radius,
  spacing,
  textStyle,
  typography,
} from '@/mobile/app/shared/theme/tokens';

export const commentPanelStyles = StyleSheet.create({
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  sheetKeyboard: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  commentSheet: {
    width: '100%',
    maxWidth: 684,
    alignSelf: 'center',
    height: '84%',
    maxHeight: '92%',
    minHeight: '84%',
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  innerSheetCard: {
    width: '100%',
    maxWidth: 684,
    alignSelf: 'center',
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    borderRadius: radius.xl,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 4,
    borderRadius: radius.pill,
    backgroundColor: colors.cardBorder,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.cardBorder,
  },
  sheetTitle: textStyle('compactTitleText', colors.text),
  sheetSubtitle: {
    marginTop: spacing.xs,
    ...typography.compactBodyText,
    color: colors.textSoft,
  },
  sheetBody: {
    flex: 1,
  },
  commentScroll: {
    flex: 1,
  },
  commentScrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    gap: spacing.md,
  },
  commentScrollContentEmpty: {
    flexGrow: 1,
  },
  emptyComments: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingVertical: spacing['2xl'],
  },
  emptyCommentsTitle: textStyle('labelText', colors.text),
  emptyCommentsDescription: textStyle('compactBodyText', colors.textSoft),
  commentNotice: {
    paddingVertical: spacing.xs,
  },
  commentStatus: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing['2xl'],
  },
  commentStatusText: textStyle('labelText', colors.textMuted),
  loadMoreButton: {
    alignItems: 'center',
    paddingVertical: spacing.xs,
  },
  loadMoreLabel: textStyle('metadataText', colors.primary, fontWeight.strong),
  commentItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    position: 'relative',
  },
  replyCommentItem: {
    marginTop: spacing.sm,
  },
  // Runs through the centre of the reply's own avatar, which sits on top of it.
  replyItemRail: {
    position: 'absolute',
    left: (avatarSize.sm - 1) / 2,
    top: -spacing.sm,
    bottom: 0,
    width: 1,
    backgroundColor: colors.cardBorder,
  },
  commentAvatarButton: {
    borderRadius: radius.pill,
    alignSelf: 'flex-start',
  },
  commentMain: {
    flex: 1,
    gap: spacing.sm,
    minWidth: 0,
  },
  replyCommentMain: {
    gap: spacing.sm,
  },
  commentBubble: {
    gap: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  replyBubble: {
    borderRadius: radius.md,
    backgroundColor: colors.background,
    borderColor: colors.cardBorder,
  },
  commentTopRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'flex-start',
  },
  commentIdentity: {
    flex: 1,
    gap: spacing.xxs,
    minWidth: 0,
  },
  commentAuthorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    minWidth: 0,
  },
  commentAuthor: {
    ...typography.labelText,
    color: colors.text,
    flexShrink: 1,
  },
  commentMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.xs,
    minWidth: 0,
  },
  commentMeta: {
    ...typography.compactBodyText,
    color: colors.textSoft,
    flexShrink: 1,
  },
  commentMetaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: colors.borderStrong,
  },
  commentEdited: {
    ...typography.metadataText,
    color: colors.primary,
    fontWeight: fontWeight.strong,
    borderRadius: radius.pill,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  commentPending: {
    ...typography.metadataText,
    color: colors.warning,
    fontWeight: fontWeight.strong,
    borderRadius: radius.pill,
    backgroundColor: colors.warningBg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  commentLikeColumn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  commentLikeAction: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentLikersAction: {
    minWidth: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentLikeButton: {
    width: 26,
    height: 26,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  commentLikeButtonActive: {
    backgroundColor: colors.dangerBg,
  },
  commentLikeCount: textStyle('metadataText', colors.textSoft, fontWeight.strong),
  commentLikeCountActive: {
    color: colors.danger,
  },
  commentContent: textStyle('captionText', colors.text, fontWeight.regular),
  replyContent: {
    ...typography.compactBodyText,
  },
  mentionText: {
    color: colors.primary,
    fontWeight: fontWeight.strong,
  },
  commentActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  commentInlineAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    minHeight: 30,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: spacing.sm,
  },
  commentInlineMenuButton: {
    width: 26,
    height: 26,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  commentInlineMenuButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  commentInlineActionText: textStyle('metadataText', colors.textMuted, fontWeight.strong),
  commentInlineActionTextActive: {
    color: colors.primary,
  },
  commentInlineDangerText: {
    color: colors.danger,
  },
  replySection: {
    gap: spacing.sm,
  },
  replyThread: {
    marginLeft: spacing.xxs,
    paddingLeft: spacing.sm,
    borderLeftWidth: 1,
    borderLeftColor: colors.cardBorder,
  },
  replyToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    alignSelf: 'flex-start',
    minHeight: 32,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: spacing.sm,
  },
  replyToggleText: textStyle('metadataText', colors.textSoft, fontWeight.strong),
  composerDock: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.cardBorder,
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
    backgroundColor: colors.background,
  },
  composerPendingText: {
    ...typography.metadataText,
    alignSelf: 'center',
    fontWeight: fontWeight.strong,
    color: colors.primary,
  },
  reactionRow: {
    gap: spacing.sm,
  },
  reactionButton: {
    width: 30,
    height: 30,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surface,
  },
  reactionButtonPressed: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.primary,
    transform: [{ scale: 0.96 }],
  },
  reactionEmoji: {
    fontSize: typography.section.fontSize,
  },
  composerBanner: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  composerBannerReply: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.primary,
  },
  composerBannerEdit: {
    backgroundColor: colors.warningBg,
    borderColor: colors.warning,
  },
  composerBannerBody: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xxs,
  },
  composerBannerText: textStyle('metadataText', colors.text, fontWeight.strong),
  composerBannerSubtext: textStyle('metadataText', colors.textSoft, fontWeight.strong),
  composerBannerActionButton: {
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  composerBannerAction: textStyle('metadataText', colors.primary, fontWeight.strong),
  composerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  composerInputWrap: {
    flex: 1,
    minHeight: 40,
    maxHeight: 82,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
  },
  composerInputWrapActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryBg,
  },
  commentInput: {
    ...typography.captionText,
    fontWeight: fontWeight.regular,
    color: colors.text,
    padding: 0,
    margin: 0,
    maxHeight: 52,
  },
  commentInputCounter: {
    alignSelf: 'flex-end',
    marginTop: spacing.xs,
    ...typography.metadataText,
    fontWeight: fontWeight.strong,
    color: colors.textSoft,
  },
  commentInputCounterWarn: {
    color: colors.warning,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  sendButtonDisabled: {
    backgroundColor: colors.surfaceMuted,
  },
  sendButtonPressed: {
    backgroundColor: colors.primaryDark,
    transform: [{ scale: 0.97 }],
  },
  disabledAction: {
    opacity: opacity.disabled,
  },
});
