import { StyleSheet } from 'react-native';

import { colors, radius, typography } from '@/mobile/app/shared/theme/tokens';

export const commentPanelStyles = StyleSheet.create({
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  sheetKeyboard: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  commentSheet: {
    width: '100%',
    maxWidth: 684,
    alignSelf: 'center',
    height: '84%',
    maxHeight: '92%',
    minHeight: '84%',
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  innerSheetCard: {
    width: '100%',
    maxWidth: 684,
    alignSelf: 'center',
    marginHorizontal: 10,
    marginBottom: 6,
    borderRadius: radius.xl,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 4,
    borderRadius: radius.pill,
    backgroundColor: colors.cardBorder,
    marginTop: 8,
    marginBottom: 10,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.cardBorder,
  },
  sheetTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  sheetSubtitle: {
    marginTop: 3,
    fontSize: 12,
    color: colors.textSoft,
  },
  sheetBody: {
    flex: 1,
  },
  commentScroll: {
    flex: 1,
  },
  commentScrollContent: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 10,
    gap: 10,
  },
  commentScrollContentEmpty: {
    flexGrow: 1,
  },
  emptyComments: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 24,
  },
  emptyCommentsTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
  },
  emptyCommentsDescription: {
    fontSize: 12,
    color: colors.textSoft,
  },
  loadMoreButton: {
    alignItems: 'center',
    paddingVertical: 4,
  },
  loadMoreLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  commentItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    position: 'relative',
  },
  replyCommentItem: {
    marginTop: 8,
  },
  replyItemRail: {
    position: 'absolute',
    left: 14,
    top: -8,
    bottom: 0,
    width: 1,
    backgroundColor: colors.cardBorder,
  },
  commentAvatarButton: {
    borderRadius: radius.pill,
    alignSelf: 'flex-start',
  },
  commentMain: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  replyCommentMain: {
    gap: 6,
  },
  commentBubble: {
    gap: 8,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surfaceRaised,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  replyBubble: {
    borderRadius: radius.md,
    backgroundColor: colors.background,
    borderColor: colors.cardBorder,
  },
  commentTopRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
  },
  commentIdentity: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  commentAuthorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minWidth: 0,
  },
  commentAuthor: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    flexShrink: 1,
  },
  commentMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 4,
    minWidth: 0,
  },
  commentMeta: {
    fontSize: 12,
    color: colors.textSoft,
    flexShrink: 1,
  },
  commentMetaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: colors.borderStrong,
  },
  commentEdited: {
    ...typography.metadataText,
    color: colors.primary,
    fontWeight: '700',
    borderRadius: radius.pill,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  commentPending: {
    ...typography.metadataText,
    color: colors.warning,
    fontWeight: '700',
    borderRadius: radius.pill,
    backgroundColor: colors.warningBg,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  commentLikeColumn: {
    minWidth: 26,
    alignItems: 'center',
    gap: 3,
  },
  commentLikeButton: {
    width: 26,
    height: 26,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  commentLikeButtonActive: {
    backgroundColor: colors.dangerBg,
  },
  commentLikeCount: {
    ...typography.metadataText,
    fontWeight: '700',
    color: colors.textSoft,
  },
  commentLikeCountActive: {
    color: colors.danger,
  },
  commentContent: {
    fontSize: 13,
    lineHeight: 19,
    color: colors.text,
  },
  replyContent: {
    fontSize: 12,
    lineHeight: 18,
  },
  mentionText: {
    color: colors.primary,
    fontWeight: '700',
  },
  commentActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  commentInlineAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 30,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 8,
  },
  commentInlineMenuButton: {
    width: 26,
    height: 26,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  commentInlineMenuButtonActive: {
    backgroundColor: colors.primaryBg,
  },
  commentInlineActionText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
  },
  commentInlineActionTextActive: {
    color: colors.primary,
  },
  commentInlineDangerText: {
    color: colors.danger,
  },
  replySection: {
    gap: 8,
  },
  replyThread: {
    marginLeft: 2,
    paddingLeft: 8,
    borderLeftWidth: 1,
    borderLeftColor: colors.cardBorder,
  },
  replyToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    minHeight: 32,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 8,
  },
  replyToggleText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSoft,
  },
  composerDock: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.cardBorder,
    paddingTop: 8,
    paddingHorizontal: 10,
    gap: 8,
    backgroundColor: colors.background,
  },
  reactionRow: {
    gap: 6,
  },
  reactionButton: {
    width: 30,
    height: 30,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surface,
  },
  reactionButtonPressed: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.primary,
    transform: [{ scale: 0.96 }],
  },
  reactionEmoji: {
    fontSize: 17,
  },
  composerBanner: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  composerBannerReply: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.primary,
  },
  composerBannerEdit: {
    backgroundColor: colors.warningBg,
    borderColor: colors.warning,
  },
  composerBannerBody: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  composerBannerText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  composerBannerSubtext: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSoft,
  },
  composerBannerActionButton: {
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  composerBannerAction: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  composerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  composerInputWrap: {
    flex: 1,
    minHeight: 40,
    maxHeight: 82,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.lg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: colors.surface,
  },
  composerInputWrapActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryBg,
  },
  commentInput: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.text,
    padding: 0,
    margin: 0,
    maxHeight: 52,
  },
  commentInputCounter: {
    alignSelf: 'flex-end',
    marginTop: 4,
    ...typography.metadataText,
    fontWeight: '700',
    color: colors.textSoft,
  },
  commentInputCounterWarn: {
    color: colors.warning,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  sendButtonDisabled: {
    backgroundColor: colors.surfaceMuted,
  },
  sendButtonPressed: {
    backgroundColor: colors.primaryDark,
    transform: [{ scale: 0.97 }],
  },
  disabledAction: {
    opacity: 0.55,
  },
});
