import { StyleSheet } from 'react-native';

import {
  avatarSize,
  colors,
  controlSize,
  fontWeight,
  opacity,
  radius,
  spacing,
  tabularNumbers,
  textStyle,
  typography,
} from '@/mobile/app/shared/theme/tokens';

export const commentPanelStyles = StyleSheet.create({
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  bottomFill: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: colors.background,
  },
  sheetKeyboard: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  commentSheet: {
    width: '100%',
    maxWidth: 684,
    alignSelf: 'center',
    height: '84%',
    maxHeight: '92%',
    minHeight: '84%',
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  innerSheetCard: {
    width: '100%',
    maxWidth: 684,
    alignSelf: 'center',
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    borderRadius: radius.xl,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 4,
    borderRadius: radius.pill,
    backgroundColor: colors.cardBorder,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  sheetHeader: {
    paddingHorizontal: spacing.screen,
  },
  sheetBody: {
    flex: 1,
  },
  commentScroll: {
    flex: 1,
  },
  commentScrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    gap: spacing.md,
  },
  commentScrollContentEmpty: {
    flexGrow: 1,
  },
  emptyComments: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingVertical: spacing['2xl'],
  },
  emptyCommentsTitle: textStyle('labelText', colors.text),
  emptyCommentsDescription: textStyle('compactBodyText', colors.textSoft),
  commentNotice: {
    paddingVertical: spacing.xs,
  },
  commentStatus: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing['2xl'],
  },
  commentStatusText: textStyle('labelText', colors.textMuted),
  loadMoreButton: {
    alignItems: 'center',
    paddingVertical: spacing.xs,
  },
  loadMoreLabel: textStyle('metadataText', colors.primary, fontWeight.strong),
  commentItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  // A reply lines up with its comment's text, not with its avatar.
  replyCommentItem: {
    marginLeft: avatarSize.sm + spacing.md,
  },
  commentAvatarButton: {
    borderRadius: radius.pill,
    alignSelf: 'flex-start',
  },
  commentMain: {
    flex: 1,
    gap: spacing.xxs,
    minWidth: 0,
  },
  commentHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minWidth: 0,
  },
  commentAuthorButton: {
    flexShrink: 1,
    minWidth: 0,
  },
  commentAuthor: textStyle('labelText', colors.text),
  commentMeta: {
    ...textStyle('compactBodyText', colors.textSoft),
    flexShrink: 0,
  },
  commentPending: textStyle('metadataText', colors.warning),
  commentContent: textStyle('bodyText', colors.text),
  // Pulled left by the icon's inset, so the heart lines up with the text.
  commentActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: -spacing.sm,
  },
  commentIconAction: {
    width: controlSize.compact,
    height: controlSize.compact,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
  },
  commentCountAction: {
    minWidth: controlSize.compact,
    height: controlSize.compact,
    justifyContent: 'center',
    paddingRight: spacing.sm,
  },
  commentTextAction: {
    height: controlSize.compact,
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    borderRadius: radius.pill,
  },
  commentMenuAction: {
    marginLeft: 'auto',
  },
  commentLikeCount: {
    ...textStyle('metadataText', colors.textSoft),
    ...tabularNumbers,
  },
  commentLikeCountActive: {
    color: colors.danger,
  },
  commentActionText: textStyle('metadataText', colors.textMuted, fontWeight.strong),
  replyToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    alignSelf: 'flex-start',
    height: controlSize.compact,
    marginLeft: -spacing.xs,
    paddingHorizontal: spacing.xs,
    borderRadius: radius.pill,
  },
  replyToggleText: textStyle('metadataText', colors.primary, fontWeight.strong),
  composerDock: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.cardBorder,
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
    backgroundColor: colors.background,
  },
  composerPendingText: {
    ...typography.metadataText,
    alignSelf: 'center',
    fontWeight: fontWeight.strong,
    color: colors.primary,
  },
  reactionRow: {
    gap: spacing.sm,
  },
  reactionButton: {
    width: 30,
    height: 30,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surface,
  },
  reactionButtonPressed: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.primary,
    transform: [{ scale: 0.96 }],
  },
  reactionEmoji: {
    fontSize: typography.section.fontSize,
  },
  composerBanner: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  composerBannerReply: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.primary,
  },
  composerBannerEdit: {
    backgroundColor: colors.warningBg,
    borderColor: colors.warning,
  },
  composerBannerBody: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xxs,
  },
  composerBannerText: textStyle('metadataText', colors.text, fontWeight.strong),
  composerBannerSubtext: textStyle('metadataText', colors.textSoft, fontWeight.strong),
  composerBannerActionButton: {
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  composerBannerAction: textStyle('metadataText', colors.primary, fontWeight.strong),
  composerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  composerInputWrap: {
    flex: 1,
    minHeight: 40,
    maxHeight: 82,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
  },
  composerInputWrapActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryBg,
  },
  commentInput: {
    ...typography.captionText,
    fontWeight: fontWeight.regular,
    color: colors.text,
    padding: 0,
    margin: 0,
    maxHeight: 52,
  },
  commentInputCounter: {
    alignSelf: 'flex-end',
    marginTop: spacing.xs,
    ...typography.metadataText,
    fontWeight: fontWeight.strong,
    color: colors.textSoft,
  },
  commentInputCounterWarn: {
    color: colors.warning,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  sendButtonDisabled: {
    backgroundColor: colors.surfaceMuted,
  },
  sendButtonPressed: {
    backgroundColor: colors.primaryDark,
    transform: [{ scale: 0.97 }],
  },
  disabledAction: {
    opacity: opacity.disabled,
  },
});
