import { StyleSheet } from 'react-native';

import {
  colors,
  controlSize,
  fontWeight,
  radius,
  spacing,
  tabularNumbers,
  textStyle,
  typography,
} from '@/mobile/app/shared/theme/tokens';

export const listEditorModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
  },
  panel: {
    width: '100%',
    maxWidth: 648,
    alignSelf: 'center',
    maxHeight: '86%',
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: radius.pill,
    backgroundColor: colors.cardBorder,
    alignSelf: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
  },
  headerText: {
    flex: 1,
  },
  title: textStyle('section', colors.text),
  subtitle: {
    marginTop: spacing.xs,
    ...typography.metadataText,
    fontWeight: fontWeight.regular,
    color: colors.textSoft,
  },
  closeButton: {
    width: controlSize.default,
    height: controlSize.default,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    gap: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
  },
  sectionCard: {
    gap: spacing.md,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  sectionTitle: textStyle('labelText', colors.text),
  sectionHint: {
    flexShrink: 1,
    textAlign: 'right',
    ...typography.metadataText,
    color: colors.textSoft,
  },
  coverPickerRow: {
    width: '100%',
    gap: spacing.sm,
  },
  coverClearButton: {
    alignSelf: 'flex-end',
    width: 26,
    height: 26,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkOverlay,
  },
  coverPicker: {
    width: '100%',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.secondary,
    backgroundColor: colors.successBg,
    gap: spacing.md,
    padding: spacing.md,
  },
  coverPickerSelected: {
    backgroundColor: colors.surface,
  },
  coverPickerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  coverPickerHeaderCopy: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },
  coverPickerIconWrap: {
    width: 34,
    height: 34,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  coverPickerBody: {
    flex: 1,
    gap: spacing.xs,
  },
  coverPickerText: textStyle('labelText', colors.secondary),
  coverPickerHint: textStyle('metadataText', colors.textMuted),
  selectionBadge: {
    minHeight: 30,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  selectionBadgeText: textStyle('metadataText', colors.textMuted, fontWeight.strong),
  fieldCount: {
    marginTop: -4,
    alignSelf: 'flex-end',
    ...typography.metadataText,
    ...tabularNumbers,
    color: colors.textSoft,
  },
  privacyRow: {
    gap: spacing.sm,
  },
  privacyButton: {
    minHeight: 64,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: colors.surfaceMuted,
  },
  privacyButtonActive: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.infoBorder,
  },
  privateButtonActive: {
    backgroundColor: colors.primaryBg,
    borderColor: colors.infoBorder,
  },
  privacyButtonBody: {
    flex: 1,
    gap: spacing.xs,
  },
  privacyText: textStyle('labelText', colors.text),
  privacyTextActivePublic: {
    color: colors.primary,
  },
  privacyTextActivePrivate: {
    color: colors.primary,
  },
  privacyCaption: textStyle('metadataText', colors.textMuted),
  privacyCaptionActivePublic: {
    color: colors.primaryDark,
  },
  privacyCaptionActivePrivate: {
    color: colors.primaryDark,
  },
  footer: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
    backgroundColor: colors.surface,
  },
  footerButton: {
    flex: 1,
  },
});
