import { StyleSheet } from 'react-native';

import {
  colors,
  elevation,
  fontWeight,
  minTouchSize,
  radius,
  spacing,
  textStyle,
  typography,
} from '@/mobile/app/shared/theme/tokens';

export const listDetailScreenStyles = StyleSheet.create({
  screenLoader: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenShell: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  scrollView: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  content: {
    paddingTop: spacing.md,
    paddingBottom: spacing.xl,
    gap: spacing.md,
    backgroundColor: colors.surface,
  },
  scrollTopButton: {
    position: 'absolute',
    right: spacing.md,
    width: minTouchSize,
    height: minTouchSize,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.text,
    ...elevation.floating,
  },
  header: {
    paddingHorizontal: spacing.md,
  },
  heroCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    ...elevation.card,
  },
  heroMediaWrap: {
    position: 'relative',
    minHeight: 144,
    backgroundColor: colors.primaryBg,
  },
  heroMediaButton: {
    minHeight: 144,
  },
  heroMedia: {
    width: '100%',
    height: 144,
  },
  heroMediaScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.imageScrim,
  },
  heroPlaceholder: {
    minHeight: 144,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    justifyContent: 'space-between',
    backgroundColor: colors.primaryBg,
  },
  heroPlaceholderBadge: {
    alignSelf: 'flex-start',
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  heroPlaceholderLabel: textStyle('labelText', colors.primaryDark),
  heroPlaceholderEmojiWrap: {
    width: 48,
    height: 48,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  heroPlaceholderEmoji: {
    ...typography.title,
  },
  coverHintChip: {
    position: 'absolute',
    bottom: spacing.sm,
    right: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: colors.darkOverlay,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  coverHintText: textStyle('labelText', colors.onPrimary),
  heroBody: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    gap: spacing.sm,
  },
  title: textStyle('title', colors.text),
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  heroMetaChip: {
    minHeight: 28,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderWidth: 1,
  },
  heroMetaChipNeutral: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.cardBorder,
  },
  heroMetaChipAccent: {
    backgroundColor: colors.successBg,
    borderColor: colors.successBorder,
  },
  heroMetaChipDanger: {
    backgroundColor: colors.dangerBg,
    borderColor: colors.dangerBorder,
  },
  heroMetaChipText: textStyle('labelText', colors.text),
  heroMetaChipTextAccent: {
    color: colors.secondary,
  },
  heroMetaChipTextDanger: {
    color: colors.danger,
  },
  heroTimestamp: {
    ...typography.captionText,
    lineHeight: typography.compactTitleText.fontSize,
    fontWeight: fontWeight.regular,
    color: colors.textSoft,
  },
  sectionStack: {
    gap: spacing.md,
    paddingHorizontal: spacing.md,
  },
  ownerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  ownerAvatarWrap: {
    width: 36,
    height: 36,
    borderRadius: radius.xl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  ownerBody: {
    flex: 1,
    minWidth: 0,
  },
  ownerEyebrow: textStyle('labelText', colors.textSoft),
  ownerName: {
    marginTop: spacing.xxs,
    ...typography.labelText,
    color: colors.text,
  },
  ownerUsername: {
    marginTop: spacing.xxs,
    ...typography.metadataText,
    color: colors.textMuted,
  },
  ownerBadge: {
    borderRadius: radius.pill,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  ownerBadgeText: textStyle('labelText', colors.primaryDark),
  descriptionCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    gap: spacing.sm,
  },
  descriptionCardLabel: textStyle('labelText', colors.textSoft),
  description: textStyle('bodyText', colors.textMuted),
  mapSection: {
    gap: spacing.sm,
  },
  mapCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  mapCardEyebrow: textStyle('labelText', colors.textSoft),
  mapCardTitle: {
    marginTop: spacing.xxs,
    ...typography.bodyText,
    fontWeight: fontWeight.strong,
    color: colors.text,
  },
  mapFrame: {
    overflow: 'hidden',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surface,
  },
  mapHelper: {
    ...typography.metadataText,
    lineHeight: typography.compactTitleText.fontSize,
    color: colors.textSoft,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginTop: spacing.xxs,
  },
  sectionHeaderCopy: {
    flex: 1,
  },
  sectionEyebrow: textStyle('labelText', colors.textSoft),
  sectionTitle: {
    marginTop: spacing.xxs,
    ...typography.section,
    color: colors.text,
  },
  sectionSubtitle: {
    marginTop: spacing.xs,
    ...typography.captionText,
    color: colors.textMuted,
  },
  feed: {
    gap: spacing.md,
  },
  feedLoader: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
  },
  // Same inset as the list header above it; without it the cards ran to the
  // screen edge and clipped their own rounded corners there.
  placeCardShell: {
    marginHorizontal: spacing.screen,
    borderRadius: radius.lg,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  placeCardShellHighlighted: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  highlightPill: {
    alignSelf: 'flex-start',
    marginBottom: spacing.sm,
    borderRadius: radius.pill,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  highlightPillText: textStyle('labelText', colors.primaryDark),
  emptyWrap: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.md,
  },
});
