import { StyleSheet } from 'react-native';

import { colors, radius, typography } from '@/mobile/app/shared/theme/tokens';

export const listDetailScreenStyles = StyleSheet.create({
  screenLoader: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenShell: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  scrollView: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  content: {
    paddingTop: 12,
    paddingBottom: 24,
    gap: 14,
    backgroundColor: colors.surface,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
    backgroundColor: colors.background,
  },
  topBarBackButton: {
    width: 44,
    height: 44,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  topBarTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.text,
  },
  topBarMeta: {
    marginTop: 2,
    fontSize: typography.micro,
    color: colors.textSoft,
  },
  topBarMenuButton: {
    width: 44,
    height: 44,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  scrollTopButton: {
    position: 'absolute',
    right: 16,
    width: 48,
    height: 48,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.text,
    shadowColor: colors.text,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  header: {
    paddingHorizontal: 16,
  },
  heroCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    shadowColor: colors.text,
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  heroMediaWrap: {
    position: 'relative',
    minHeight: 168,
    backgroundColor: colors.primaryBg,
  },
  heroMediaButton: {
    minHeight: 168,
  },
  heroMedia: {
    width: '100%',
    height: 168,
  },
  heroMediaScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.shadowSubtle,
  },
  heroPlaceholder: {
    minHeight: 168,
    paddingHorizontal: 16,
    paddingVertical: 16,
    justifyContent: 'space-between',
    backgroundColor: colors.primaryBg,
  },
  heroPlaceholderBadge: {
    alignSelf: 'flex-start',
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  heroPlaceholderLabel: {
    fontSize: typography.micro,
    fontWeight: '800',
    color: colors.primaryDark,
  },
  heroPlaceholderEmojiWrap: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  heroPlaceholderEmoji: {
    fontSize: 24,
  },
  coverHintChip: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: radius.pill,
    backgroundColor: colors.darkOverlay,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  coverHintText: {
    fontSize: typography.micro,
    fontWeight: '800',
    color: colors.onPrimary,
  },
  heroBody: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 14,
    gap: 10,
  },
  title: {
    fontSize: typography.screenTitle,
    lineHeight: 28,
    fontWeight: '800',
    color: colors.text,
  },
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  heroMetaChip: {
    minHeight: 28,
    borderRadius: radius.pill,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
  },
  heroMetaChipNeutral: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.cardBorder,
  },
  heroMetaChipAccent: {
    backgroundColor: colors.successBg,
    borderColor: 'rgba(16,185,129,0.18)',
  },
  heroMetaChipDanger: {
    backgroundColor: colors.dangerBg,
    borderColor: 'rgba(239,68,68,0.18)',
  },
  heroMetaChipText: {
    fontSize: typography.micro,
    fontWeight: '800',
    color: colors.text,
  },
  heroMetaChipTextAccent: {
    color: colors.secondary,
  },
  heroMetaChipTextDanger: {
    color: colors.danger,
  },
  heroTimestamp: {
    fontSize: typography.micro,
    lineHeight: 16,
    color: colors.textSoft,
  },
  sectionStack: {
    gap: 12,
    paddingHorizontal: 16,
  },
  ownerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  ownerAvatarWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  ownerBody: {
    flex: 1,
    minWidth: 0,
  },
  ownerEyebrow: {
    fontSize: typography.micro,
    fontWeight: '800',
    color: colors.textSoft,
    textTransform: 'uppercase',
  },
  ownerName: {
    marginTop: 2,
    fontSize: 15,
    fontWeight: '800',
    color: colors.text,
  },
  ownerUsername: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textMuted,
  },
  ownerBadge: {
    borderRadius: radius.pill,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  ownerBadgeText: {
    fontSize: typography.micro,
    fontWeight: '800',
    color: colors.primaryDark,
  },
  descriptionCard: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
  },
  descriptionCardLabel: {
    fontSize: typography.micro,
    fontWeight: '800',
    color: colors.textSoft,
    textTransform: 'uppercase',
  },
  description: {
    fontSize: 13,
    lineHeight: 20,
    color: colors.textMuted,
  },
  mapSection: {
    gap: 8,
  },
  mapCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  mapCardEyebrow: {
    fontSize: typography.micro,
    fontWeight: '800',
    color: colors.textSoft,
    textTransform: 'uppercase',
  },
  mapCardTitle: {
    marginTop: 2,
    fontSize: 16,
    fontWeight: '800',
    color: colors.text,
  },
  mapFrame: {
    overflow: 'hidden',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.surface,
  },
  mapHelper: {
    fontSize: 11,
    lineHeight: 16,
    color: colors.textSoft,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 2,
  },
  sectionHeaderCopy: {
    flex: 1,
  },
  sectionEyebrow: {
    fontSize: typography.micro,
    fontWeight: '800',
    color: colors.textSoft,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    marginTop: 2,
    fontSize: typography.sectionTitle,
    fontWeight: '800',
    color: colors.text,
  },
  sectionSubtitle: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textMuted,
  },
  feed: {
    gap: 14,
  },
  feedLoader: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  placeCardShell: {
    borderRadius: radius.lg,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  placeCardShellHighlighted: {
    borderWidth: 2,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  highlightPill: {
    alignSelf: 'flex-start',
    marginBottom: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  highlightPillText: {
    fontSize: typography.micro,
    fontWeight: '800',
    color: colors.primaryDark,
  },
  emptyWrap: {
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
});
