/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 8293315909e946f0c7c2078e93e22277)
interface __BaseEnv_Env {
	AUTH_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	BUILD_SHA: string;
	ENVIRONMENT: string;
	SUPABASE_URL: string;
	SUPABASE_JWT_AUDIENCE: string;
	CORS_ALLOWLIST: string;
	ORIGIN_TIMEOUT_MS: string;
	JWKS_TIMEOUT_MS: string;
	LOG_SAMPLE_RATE: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	ORIGIN_HMAC_SECRET: string;
	IP_HASH_PEPPER: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface DevelopmentEnv {
		AUTH_RATE_LIMITER: RateLimit;
		API_RATE_LIMITER: RateLimit;
		BUILD_SHA: string;
		ENVIRONMENT: string;
		SUPABASE_URL: string;
		SUPABASE_JWT_AUDIENCE: string;
		CORS_ALLOWLIST: string;
		ORIGIN_TIMEOUT_MS: string;
		JWKS_TIMEOUT_MS: string;
		LOG_SAMPLE_RATE: string;
		SUPABASE_PUBLISHABLE_KEY: string;
		ORIGIN_HMAC_SECRET: string;
		IP_HASH_PEPPER: string;
	}
	interface PreviewEnv {
		AUTH_RATE_LIMITER: RateLimit;
		API_RATE_LIMITER: RateLimit;
		BUILD_SHA: string;
		ENVIRONMENT: string;
		SUPABASE_URL: string;
		SUPABASE_JWT_AUDIENCE: string;
		CORS_ALLOWLIST: string;
		ORIGIN_TIMEOUT_MS: string;
		JWKS_TIMEOUT_MS: string;
		LOG_SAMPLE_RATE: string;
		SUPABASE_PUBLISHABLE_KEY: string;
		ORIGIN_HMAC_SECRET: string;
		IP_HASH_PEPPER: string;
	}
	interface ProductionEnv {
		AUTH_RATE_LIMITER: RateLimit;
		API_RATE_LIMITER: RateLimit;
		BUILD_SHA: string;
		ENVIRONMENT: string;
		SUPABASE_URL: string;
		SUPABASE_JWT_AUDIENCE: string;
		CORS_ALLOWLIST: string;
		ORIGIN_TIMEOUT_MS: string;
		JWKS_TIMEOUT_MS: string;
		LOG_SAMPLE_RATE: string;
		SUPABASE_PUBLISHABLE_KEY: string;
		ORIGIN_HMAC_SECRET: string;
		IP_HASH_PEPPER: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BUILD_SHA" | "ENVIRONMENT" | "SUPABASE_URL" | "SUPABASE_JWT_AUDIENCE" | "CORS_ALLOWLIST" | "ORIGIN_TIMEOUT_MS" | "JWKS_TIMEOUT_MS" | "LOG_SAMPLE_RATE" | "SUPABASE_PUBLISHABLE_KEY" | "ORIGIN_HMAC_SECRET" | "IP_HASH_PEPPER">> {}
}
