export const PLACE_MEDIA_MAX_VIDEO_DURATION_SECONDS = 60;
export const PLACE_MEDIA_MAX_VIDEO_DURATION_MS = PLACE_MEDIA_MAX_VIDEO_DURATION_SECONDS * 1000;
export const PLACE_MEDIA_TARGET_VIDEO_QUALITY = '720p' as const;
export const PLACE_MEDIA_TARGET_VIDEO_BITRATE = 5_000_000;
