import { Platform, StyleSheet } from 'react-native';

import { colors, radius, touch, typography } from '@/mobile/app/shared/theme/tokens';

export const placeCardStyles = StyleSheet.create({
  feedCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.cardBorder,
    position: 'relative',
  },
  userHeader: {
    minHeight: Platform.OS === 'ios' ? touch.ios : touch.android,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 2,
  },
  userBody: {
    flex: 1,
  },
  userName: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
    color: colors.text,
  },
  userUsername: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textSoft,
  },
  sourceBar: {
    minHeight: Platform.OS === 'ios' ? touch.ios : touch.android,
    marginHorizontal: 12,
    marginTop: 6,
    borderRadius: 14,
    backgroundColor: colors.purpleBg,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 8,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sourceAvatarWrap: {
    position: 'relative',
  },
  sourceBarIcon: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.quote,
    borderWidth: 2,
    borderColor: colors.purpleBg,
  },
  sourceBarBody: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  sourceBarTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minWidth: 0,
  },
  sourceBarTitle: {
    ...typography.metadataText,
    fontWeight: '700',
    color: colors.text,
    flexShrink: 1,
  },
  sourceBarUsername: {
    ...typography.metadataText,
    fontWeight: '700',
    color: colors.textSoft,
    flexShrink: 1,
  },
  sourceBarMeta: {
    ...typography.metadataText,
    fontWeight: '600',
    color: colors.quote,
  },
  linkBar: {
    minHeight: Platform.OS === 'ios' ? touch.ios : touch.android,
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 8,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  linkBarCover: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
  },
  linkBarCoverFallback: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  linkBarBody: {
    flex: 1,
    minWidth: 0,
  },
  linkBarTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  linkBarTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  linkBarMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 3,
  },
  linkBarMetaText: {
    ...typography.metadataText,
    fontWeight: '600',
    color: colors.textSoft,
  },
  linkBarMetaTextPrivate: {
    color: colors.visibilityPrivate,
  },
  mapWrap: {
    paddingHorizontal: 12,
    marginTop: 8,
  },
  mediaCarouselWrap: {
    marginHorizontal: 12,
    marginTop: 8,
    aspectRatio: 1.28,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: colors.deepBackground,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  mediaCarousel: {
    flex: 1,
  },
  mediaCarouselPage: {
    height: '100%',
  },
  mediaCarouselMedia: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.deepBackground,
  },
  mediaCarouselCounter: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.darkOverlay,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  mediaCarouselCounterText: {
    ...typography.metadataText,
    fontWeight: '700',
    color: colors.onPrimary,
  },
  locationBar: {
    minHeight: 32,
    marginHorizontal: 12,
    marginTop: 8,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.cardBorder,
    borderRadius: 11,
    backgroundColor: colors.surfaceMuted,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  locationIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryBg,
  },
  locationText: {
    ...typography.metadataText,
    flex: 1,
    color: colors.textMuted,
    fontWeight: '700',
    letterSpacing: 0.1,
  },
  content: {
    paddingHorizontal: 12,
    paddingTop: 10,
    gap: 4,
  },
  contentTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  contentTitleButton: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
    minWidth: 0,
    borderRadius: 8,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  contentTitleButtonInteractive: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contentTitleButtonPressed: {
    backgroundColor: colors.primaryBg,
  },
  contentTitleInline: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    maxWidth: '100%',
    minWidth: 0,
    gap: 4,
  },
  contentTitleStack: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
    minWidth: 0,
    gap: 2,
  },
  contentTitleContent: {
    flex: 1,
    minWidth: 0,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.secondary,
  },
  title: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '700',
    color: colors.text,
    flexShrink: 1,
  },
  titleLink: {
    color: colors.text,
  },
  titleMeta: {
    ...typography.metadataText,
    fontWeight: '600',
    color: colors.textSoft,
  },
  contentTitleChevron: {
    flexShrink: 0,
  },
  description: {
    ...typography.captionText,
    color: colors.textMuted,
  },
  menuAction: {
    alignSelf: 'flex-start',
    minHeight: 40,
    maxWidth: '100%',
    marginTop: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
    justifyContent: 'center',
  },
  menuActionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  menuActionPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
  menuActionIcon: {
    width: 18,
    height: 18,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  menuActionLabel: {
    ...typography.metadataText,
    fontWeight: '700',
    color: colors.primary,
  },
  menuUrlPreview: {
    maxWidth: 270,
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.borderStrong,
    gap: 4,
  },
  menuUrlText: {
    ...typography.metadataText,
    color: colors.textMuted,
  },
  menuHoldHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  menuHoldHintText: {
    ...typography.metadataText,
    color: colors.textSoft,
  },
  timestampBlock: {
    paddingTop: 1,
  },
  timestampText: {
    ...typography.metadataText,
    color: colors.textDisabled,
  },
  tagSection: {
    gap: 4,
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  moreFeaturesButton: {
    minHeight: Platform.OS === 'ios' ? touch.ios : touch.android,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: radius.pill,
    paddingHorizontal: 8,
    backgroundColor: colors.primaryBg,
  },
  moreFeaturesText: {
    ...typography.metadataText,
    color: colors.primary,
    fontWeight: '700',
  },
  badgeRow: {
    gap: 6,
    alignItems: 'center',
  },
  badge: {
    borderRadius: radius.pill,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.surfaceMuted,
  },
  badgeText: {
    ...typography.metadataText,
    fontWeight: '600',
    color: colors.textMuted,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.warningBg,
  },
  ratingBadgeText: {
    color: colors.warningText,
  },
  studentBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primaryBg,
  },
  studentBadgeText: {
    color: colors.primary,
  },
  purpleBadge: {
    backgroundColor: colors.purpleBg,
  },
  purpleBadgeText: {
    color: colors.purple,
  },
  greenBadge: {
    backgroundColor: colors.successBg,
  },
  greenBadgeText: {
    color: colors.secondary,
  },
  inlineIcon: {
    justifyContent: 'center',
  },
});
