import { compareLocalizedText, uniqueSortedText } from '@/mobile/app/shared/utils/textSort';

const categoryEntries = [
  { value: 'aquarium', label: 'Akvaryum' },
  { value: 'amusementcenter', label: 'Aktivite Merkezi' },
  { value: 'airport', label: 'Havalimanı' },
  { value: 'antikaci', label: 'Antikacı' },
  { value: 'artcenter', label: 'Sanat Merkezi' },
  { value: 'artgallery', label: 'Sanat Galerisi' },
  { value: 'asianrestaurant', label: 'Asya Mutfağı' },
  { value: 'atolye', label: 'Atölye' },
  { value: 'bakery', label: 'Fırın / Pastane' },
  { value: 'bar', label: 'Bar' },
  { value: 'bazaar', label: 'Çarşı / Pazar' },
  { value: 'beach', label: 'Plaj' },
  { value: 'beachclub', label: 'Beach Club' },
  { value: 'bistro', label: 'Bistro' },
  { value: 'boatTour', label: 'Tekne Turu Noktası' },
  { value: 'bookstore', label: 'Kitapçı' },
  { value: 'boutique', label: 'Butik' },
  { value: 'breakfast', label: 'Kahvaltıcı' },
  { value: 'brewery', label: 'Bira Evi' },
  { value: 'brunchspot', label: 'Brunch Mekanı' },
  { value: 'burger', label: 'Burgerci' },
  { value: 'cafe', label: 'Kafe' },
  { value: 'camping', label: 'Kamp Alanı' },
  { value: 'campus', label: 'Kampüs Noktası' },
  { value: 'cinema', label: 'Sinema' },
  { value: 'cocktailbar', label: 'Kokteyl Barı' },
  { value: 'concerthall', label: 'Konser Salonu' },
  { value: 'coworking', label: 'Coworking' },
  { value: 'dessert', label: 'Tatlıcı' },
  { value: 'doner', label: 'Dönerci' },
  { value: 'escapeRoom', label: 'Escape Room' },
  { value: 'ethnicrestaurant', label: 'Dünya Mutfağı' },
  { value: 'eventvenue', label: 'Etkinlik Alanı' },
  { value: 'fastfood', label: 'Fast Food' },
  { value: 'ferry', label: 'İskele / Vapur' },
  { value: 'fishmarket', label: 'Balık Pazarı' },
  { value: 'forest', label: 'Orman / Mesire' },
  { value: 'garden', label: 'Botanik Bahçe' },
  { value: 'gelato', label: 'Gelato / Dondurma' },
  { value: 'gym', label: 'Spor Salonu' },
  { value: 'historicsite', label: 'Tarihi Mekan' },
  { value: 'hookahlounge', label: 'Nargile Kafe' },
  { value: 'hostel', label: 'Hostel' },
  { value: 'hotel', label: 'Otel' },
  { value: 'icecream', label: 'Dondurmacı' },
  { value: 'juicebar', label: 'Meyve Suyu / Smoothie' },
  { value: 'kebab', label: 'Kebapçı' },
  { value: 'library', label: 'Kütüphane' },
  { value: 'lokanta', label: 'Lokanta' },
  { value: 'market', label: 'Market' },
  { value: 'meyhane', label: 'Meyhane' },
  { value: 'mosque', label: 'Cami' },
  { value: 'museum', label: 'Müze' },
  { value: 'musicvenue', label: 'Müzik Mekanı' },
  { value: 'nightclub', label: 'Gece Kulübü' },
  { value: 'nightlife', label: 'Gece Hayatı' },
  { value: 'observatory', label: 'Gözlem Noktası' },
  { value: 'other', label: 'Diğer' },
  { value: 'park', label: 'Park' },
  { value: 'patisserie', label: 'Pastane' },
  { value: 'petfriendlycafe', label: 'Pet Dostu Kafe' },
  { value: 'pilatesstudio', label: 'Pilates Stüdyosu' },
  { value: 'pizzeria', label: 'Pizzacı' },
  { value: 'pool', label: 'Havuz' },
  { value: 'pub', label: 'Pub' },
  { value: 'ramen', label: 'Ramen / Noodle' },
  { value: 'restaurant', label: 'Restoran' },
  { value: 'roastery', label: 'Kahve Kavurma Evi' },
  { value: 'rooftop', label: 'Rooftop' },
  { value: 'seafood', label: 'Balık / Deniz Ürünü' },
  { value: 'shopping', label: 'Alışveriş' },
  { value: 'spa', label: 'Spa / Hamam' },
  { value: 'sport', label: 'Spor Tesisi' },
  { value: 'steakhouse', label: 'Et Restoranı' },
  { value: 'streetfood', label: 'Sokak Lezzetleri' },
  { value: 'studycafe', label: 'Çalışma Kafesi' },
  { value: 'sushi', label: 'Suşi' },
  { value: 'teahouse', label: 'Çay Evi' },
  { value: 'theater', label: 'Tiyatro' },
  { value: 'themepark', label: 'Eğlence Parkı' },
  { value: 'veganrestaurant', label: 'Vegan / Sağlıklı Mutfak' },
  { value: 'viewpoint', label: 'Manzara Noktası' },
  { value: 'vintageStore', label: 'Vintage Dükkan' },
  { value: 'watersports', label: 'Su Sporları' },
  { value: 'winery', label: 'Şarap Evi' },
  { value: 'workshop', label: 'Deneyim Alanı' },
  { value: 'yoga', label: 'Yoga / Meditasyon' },
  { value: 'zoo', label: 'Hayvanat Bahçesi' },
];

const atmosphereOptions = [
  'Açık hava',
  'Aile dostu',
  'Alternatif',
  'Aristokrat',
  'Aydınlık',
  'Bohem',
  'Butik',
  'Canlı',
  'Canlı ve sosyal',
  'Coşkulu',
  'Cozy',
  'Çalışmaya uygun',
  'Deniz esintili',
  'Dinamik',
  'Doğal',
  'Dramatik',
  'Durgun ve sakin',
  'Eğlenceli',
  'Enerjik',
  'Endüstriyel',
  'Erişilebilir',
  'Ferah',
  'Festival havası',
  'Genç',
  'Geleneksel',
  'Gölgeli',
  'Gösterişli',
  'Gurme',
  'Hareketli',
  'Huzurlu',
  'İddialı',
  'İlham verici',
  'İnzivaya uygun',
  'Kalabalık',
  'Konforlu',
  'Lokal',
  'Loş',
  'Lüks',
  'Mahalle sıcaklığı',
  'Manzaralı',
  'Masalsı',
  'Meditatif',
  'Minimal',
  'Modern',
  'Motivasyon verici',
  'Müzikli',
  'Nostaljik',
  'Otantik',
  'Panoramik',
  'Rahat',
  'Renkli',
  'Retro',
  'Romantik',
  'Rustik',
  'Sakin',
  'Samimi',
  'Sanatsal',
  'Sessiz',
  'Sofistike',
  'Sosyal',
  'Sportif',
  'Şehirli',
  'Şık',
  'Tarihi',
  'Taze ve canlı',
  'Tropik',
  'Turistik',
  'Underground',
  'Urban',
  'Vintage',
  'Yaratıcı',
  'Yavaş tempolu',
  'Yüksek enerjili',
  'Zen',
];

const featureOptions = [
  'Açık alan',
  'Açık büfe',
  'Açık mutfak',
  'Aile alanı',
  'Alkol servisi',
  'Arabaya servis',
  'Bahçe',
  'Bar oturma alanı',
  'Bebek bakım odası',
  'Bebek sandalyesi',
  'Bisiklet parkı',
  'Board game',
  'Brunch',
  'Canlı müzik',
  'Çalışma dostu masa',
  'Çalışma odası',
  'Çocuk alanı',
  'Çocuk menüsü',
  'Deniz manzarası',
  'DJ performansı',
  'Elektrikli araç şarjı',
  'Engelli erişimi',
  'Etkinlik takvimi',
  'Evcil hayvan dostu',
  'Filtre kahve',
  'Fine dining',
  'Glisemik denge dostu seçenek',
  'Glutensiz seçenek',
  'Göl manzarası',
  'Gün batımı manzarası',
  'Hızlı servis',
  'Helal seçenek',
  'Isıtmalı dış alan',
  'İftar menüsü',
  'Instagram için uygun',
  'Kahvaltı',
  'Kahve çekirdeği satışı',
  'Kapalı otopark',
  'Klima',
  'Kokteyl menüsü',
  'Konsept dekorasyon',
  'Kutlama için uygun',
  'Kütüphane köşesi',
  'Laktozsuz seçenek',
  'Masa servisi',
  'Meyhane servisi',
  'Mikrodalga / mutfak erişimi',
  'Müzik yayını',
  'Online rezervasyon',
  'Ortak masa',
  'Otopark',
  'Oyun alanı',
  'Paket servis',
  'Paylaşımlı tabaklar',
  'Premium kahve',
  'Priz',
  'QR menü',
  'Rezervasyon gerekli',
  'Rezervasyonsuz oturum',
  'Rooftop',
  'Sessiz alan',
  'Sigara alanı',
  'Sınırsız internet',
  'Slow food',
  'Sokak oturumu',
  'Su kenarı',
  'Tatlı vitrini',
  'Teras',
  'Toplantı alanı',
  'Vale',
  'Vegan seçenek',
  'Vejetaryen seçenek',
  'WiFi',
  'Yerel lezzetler',
  'Yüksek tavan',
  'Özel oda',
  'Protein odaklı menü',
  'Şarj noktası',
  'Şekersiz seçenek',
];

const bestTimeOptions = [
  'Akşam',
  'Ara sıcak saatleri',
  'Bayramlar',
  'Brunch saati',
  'Canlı müzik saatleri',
  'Erken akşam',
  'Erken kahvaltı',
  'Gece',
  'Gece yarısı',
  'Geç kahvaltı',
  'Gün boyu',
  'Gün içi',
  'Gün batımı',
  'Gün doğumu',
  'Happy hour',
  'Hafta içi',
  'Hafta sonu',
  'Her zaman',
  'İftar vakti',
  'İlkbahar',
  'İş çıkışı',
  'Kahve molası',
  'Kapanışa yakın',
  'Kış',
  'Lunch saati',
  'Maç saatleri',
  'Öğle arası',
  'Öğle molası',
  'Öğleden sonra',
  'Öğlen',
  'Özel günler',
  'Pazar sabahı',
  'Ramazan',
  'Sabah',
  'Sessiz saatler',
  'Sınav dönemi',
  'Sonbahar',
  'Tatlı saati',
  'Tatil günleri',
  'Yaz',
  'Yaz akşamı',
  'Yağmurlu hava',
  'Yılbaşı',
];

export const PLACE_CATEGORY_OPTIONS = [...categoryEntries]
  .filter((item, index, array) => array.findIndex((candidate) => candidate.value === item.value) === index)
  .sort((a, b) => compareLocalizedText(a.label, b.label));

export const PLACE_CATEGORY_META = Object.fromEntries(
  PLACE_CATEGORY_OPTIONS.map((item) => [item.value, { label: item.label, emoji: '' }]),
) as Record<string, { label: string; emoji: string }>;

export const PLACE_ATMOSPHERE_OPTIONS = uniqueSortedText(atmosphereOptions);

export const PLACE_FEATURE_OPTIONS = uniqueSortedText(featureOptions);

export const PLACE_BEST_TIME_OPTIONS = uniqueSortedText(bestTimeOptions);

export const PLACE_DIETARY_OPTIONS = uniqueSortedText([
  'Glisemik denge dostu seçenek',
  'Glutensiz seçenek',
  'Helal seçenek',
  'Laktozsuz seçenek',
  'Protein odaklı menü',
  'Şekersiz seçenek',
  'Vegan seçenek',
  'Vejetaryen seçenek',
]);
